<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><div><h2 class="text-xl font-bold">Atualização da VNL</h2><p class="text-sm text-slate-500">Fonte: Volleyball World</p></div><form method="POST" action="{{ route('admin.scraping.atualizar') }}" onsubmit="this.querySelector('button').disabled=true;this.querySelector('button').innerText='Atualizando...'">@csrf<button class="rounded-lg bg-blue-700 px-4 py-2.5 text-sm font-bold text-white">Atualizar dados da VNL</button></form></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-6xl px-4">
        @include('admin.partials.flash')
        @if(session('error'))<div class="mb-5 rounded-xl bg-red-50 p-4 text-red-700">{{ session('error') }}</div>@endif
        <div class="mb-6 rounded-2xl border border-blue-200 bg-blue-50 p-5 text-sm text-blue-900"><strong>Plano B preservado:</strong> falhas no scraping não removem dados. Partidas e classificação continuam editáveis manualmente nos respectivos CRUDs.</div>
        <div class="space-y-4">@forelse($logs as $log)<article class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div class="flex flex-wrap justify-between gap-3"><div><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $log->status==='sucesso'?'bg-emerald-100 text-emerald-700':($log->status==='erro'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700') }}">{{ strtoupper($log->status) }}</span><h3 class="mt-3 font-bold">{{ $log->mensagem }}</h3></div><div class="text-right text-sm text-slate-500">{{ $log->iniciado_em->format('d/m/Y H:i:s') }}<br>{{ $log->registros_processados }} registros</div></div>@if($log->detalhes)<pre class="mt-4 overflow-x-auto rounded-lg bg-slate-950 p-4 text-xs text-slate-100">{{ json_encode($log->detalhes, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre>@endif</article>@empty<p class="rounded-2xl bg-white p-10 text-center text-slate-500">Nenhuma execução registrada.</p>@endforelse</div><div class="mt-5">{{ $logs->links() }}</div>
    </div></div>
</x-app-layout>
